name: 'composite-test'
description: 'composite-test'

inputs:
  secrets_json:
    description: all secrets json
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup yq
      uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.30.6
    - name: Action Test
      shell: bash
      run: |
        for s in $(echo '${{ inputs.secrets_json }}' | jq  -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]"); do
          echo $s >> $GITHUB_ENV
          echo $s
        done
        echo $GITHUB_ENV
