name: 'composite-test'
description: 'composite-test'

inputs:
  secrets_json:
    description: all secrets json
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup yq
      uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.30.6
    - name: Action Test
      shell: bash
      run: |
        echo ${{ inputs.secrets_json }}

        echo jq ${{ inputs.secrets_json }} -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]");
