name: 'composite-test'
description: 'composite-test'

runs:
  using: 'composite'
  steps:
    - name: Setup yq
      uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.30.6
    - name: Action Test
      shell: bash
      env:
        ALLMYSECRETS: ${{ toJSON(secrets) }}
      run: |
        echo ${{ env.ALLMYSECRETS }}

        echo jq ${{ env.ALLMYSECRETS }} -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]");
