name: 'composite-test'
description: 'composite-test'

runs:
  using: 'composite'
  steps:
    - name: Action Test
      shell: bash
      env:
        ALLMYSECRETS: ${{ toJSON(secrets) }}
        ALLMYVARS: ${{ toJSON(vars) }}
      run: |
        echo ${{ ALLMYSECRETS }}
        echo ${{ ALLMYVARS }}

        echo jq ALLMYSECRETS -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]");
