name: TestMessage

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: Git Ref ID(commit id | tag | branch)
        required: true
        default: develop

jobs:
  task-running:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    environment:
        name: ${{github.event.inputs.git_ref}}

    steps:
      - name: Test Message
        shell: bash
        env:
          TEST_MESSAGE: ${{secrets.TEST_MESSAGE}}
        run: |
          echo ${{env.TEST_MESSAGE}} | sed 's/./& /g';
