name: TestMessage

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: Git Ref ID(commit id | tag | branch)
        required: true
        default: develop

jobs:
  task-running:
    name: Test Actions
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    environment:
        name: ${{github.event.inputs.git_ref}}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_REF }}
      - name: Action Test
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
        run: |
          echo ${{ env.ALLMYSECRETS }}
          echo ${{ env.ALLMYVARS }}
      - name: Test Actions
        id: test_actions
        uses: ./.github/actions/composite-test
